name: github-action

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2.5', '9.4.5', '9.6.1', '9.8.2', '9.10.1']
        os: ['ubuntu-latest', 'macos-latest']
    runs-on: ${{ matrix.os }}

    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-${{ matrix.ghc }}-build-
          ${{ runner.os }}-${{ matrix.ghc }}-
          ${{ runner.os }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
        touch nix-prefetch-git
        touch nix-prefetch-url
        chmod 755 nix-prefetch-git nix-prefetch-url

    - name: Build
      run: env PATH=.:$PATH cabal build --enable-tests --enable-benchmarks all

    - name: Run tests
      run: env PATH=.:$PATH cabal test --enable-tests all

    - name: Build Docs
      run: cabal haddock
